version: "3.6"
services:
  nodeapi:
    build:
      context: ./
      dockerfile: DOCKERFILE
    container_name: nodeapi
    restart: unless-stopped
    ports:
      - 3002:5000
    volumes:
      - ./:/home/node/app/

  drynode_1:
    build:
      context: ./
      dockerfile: LocalDryNetworkDockerfile
      args:
        - "SOURCE_CHAIN_RPC_ENDPOINT='https://speedy-nodes-nyc.moralis.io/e2c7f1070d3a8aba5cdbd7b4/bsc/mainnet/archive'"
        - "ACCOUNT_TO_UNLOCK=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
    container_name: drynode_1
    restart: unless-stopped
    ports:
      - 8558:8545
  drynode_2:
    build:
      context: ./
      dockerfile: LocalDryNetworkDockerfile
      args:
        - "SOURCE_CHAIN_RPC_ENDPOINT='https://speedy-nodes-nyc.moralis.io/e2c7f1070d3a8aba5cdbd7b4/bsc/mainnet/archive'"
        - "ACCOUNT_TO_UNLOCK=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
    container_name: drynode_2
    restart: unless-stopped
    ports:
      - 8556:8545
  drynode_3:
    build:
      context: ./
      dockerfile: LocalDryNetworkDockerfile
      args:
        - "SOURCE_CHAIN_RPC_ENDPOINT='https://speedy-nodes-nyc.moralis.io/<>/bsc/mainnet/archive'"
        - "ACCOUNT_TO_UNLOCK=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
    container_name: drynode_3
    restart: unless-stopped
    ports:
      - 8557:8545
  drynode_4:
    build:
      context: ./
      dockerfile: LocalDryNetworkDockerfile
      args:
        - "SOURCE_CHAIN_RPC_ENDPOINT='https://speedy-nodes-nyc.moralis.io/<>/bsc/mainnet/archive'"
        - "ACCOUNT_TO_UNLOCK=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
    container_name: drynode_4
    restart: unless-stopped
    ports:
      - 8560:8545
  drynode_5:
    build:
      context: ./
      dockerfile: LocalDryNetworkDockerfile
      args:
        - "SOURCE_CHAIN_RPC_ENDPOINT='https://speedy-nodes-nyc.moralis.io/<>/bsc/mainnet/archive'"
        - "ACCOUNT_TO_UNLOCK=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
    container_name: drynode_5
    restart: unless-stopped
    ports:
      - 8561:8545
  drynode_6:
    build:
      context: ./
      dockerfile: LocalDryNetworkDockerfile
      args:
        - "SOURCE_CHAIN_RPC_ENDPOINT='https://speedy-nodes-nyc.moralis.io/<>/bsc/mainnet/archive'"
        - "ACCOUNT_TO_UNLOCK=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
    container_name: drynode_6
    restart: unless-stopped
    ports:
      - 8562:8545
  drynode_7:
    build:
      context: ./
      dockerfile: LocalDryNetworkDockerfile
      args:
        - "SOURCE_CHAIN_RPC_ENDPOINT='https://speedy-nodes-nyc.moralis.io/<>/bsc/mainnet/archive'"
        - "ACCOUNT_TO_UNLOCK=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
    container_name: drynode_7
    restart: unless-stopped
    ports:
      - 8563:8545
