rpcNodes:
  - http://localhost:8555
must_exist_node: https://speedy-nodes-nyc.moralis.io/<>/bsc/mainnet #moralis doesn't have archive nodes anymore, this is just for reference
exec_node:
  mainNet: https://speedy-nodes-nyc.moralis.io/<>/bsc/mainnet #moralis doesn't have archive nodes anymore, this is just for reference

